eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}-${server.port}
    #instance-id: ${spring.application.name}-${random.int}
emp:
  service:
       url: "localhost:8080/employee-service/employee/getEmplist"
